# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: PostgreSQL 17
      POSTGRES_USER: arleswasb  
      POSTGRES_PASSWORD: postarl
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: