# docker-compose.yml
# VERSÃO FINAL REVISADA


services:
  # O nome do serviço pode ser 'db' ou 'postgres', ambos são comuns.
  # Usarei 'postgres' para manter a consistência com o exemplo anterior.
  postgres:
    image: postgres:16
    container_name: biblioteca_postgres_local
    restart: always
    
    # CORREÇÃO: Carrega as variáveis diretamente do seu arquivo .env
    # O Docker Compose irá procurar por POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB neste arquivo.
    env_file:
      - .env
      
    ports:
      - "5432:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Declaração do volume para garantir a persistência dos dados
volumes:
  postgres_data: